name: UnityBuild 😎

on:
  pull_request: {}
  push: { branches: [master] }

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  build:
    name: Build my project ✨
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true

      # Cache
      - uses: actions/cache@v1.1.0
        with:
          path: Library
          key: Library

      # Test
      - name: Run tests
        uses: webbertakken/unity-test-runner@v1.3
        with:
          unityVersion: 2019.3.0f6

      # Build
      - name: Build project
        uses: webbertakken/unity-builder@master
        with:
          unityVersion: 2019.3.0f6
          customImage: gableroux/unity3d:2019.3.0f1@6cfc56c1f7404420fbf74a2086b8f86b89affc9bcc9566edf599737583c2e115
          targetPlatform: WebGL

      # Output
      - uses: actions/upload-artifact@v1
        with:
          name: Build
          path: build