name: UnityBuild v2

on:
  pull_request: {}
  push: { branches: [master] }

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE2 }}

jobs:
  build:
    name: Build my project ✨
    runs-on: ubuntu-latest
    steps:

      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true

      # Cache
      - uses: actions/cache@v1.1.0
        with:
          path: Library
          key: Library

      # Build
      - name: Build project
        uses: webbertakken/unity-builder@v1.2
        with:
          unityVersion: 2019.3.0f6
          customImage: gableroux/unity3d@sha256:35021c97d5ace11fa413aa908e4bb20ab3c17548aad620e18bdd571e7893d08e
          targetPlatform: Android

      # Output
      - uses: actions/upload-artifact@v1
        with:
          name: Build
          path: 
            build
            profile_build_run
            /root/.gradle/daemon/5.1.1/*.out.log